export const JOB_CATEGORIES = [
  "WEB_DEVELOPMENT",
  "APP_DEVELOPMENT",
  "UI_UX_DESIGN",
  "GRAPHIC_DESIGN",
  "CONTENT_WRITING",
  "VIDEO_EDITING",
  "DIGITAL_MARKETING",
  "SEO",
  "DATA_ENTRY",
  "DATA_ANALYSIS",
  "SOFTWARE_TESTING",
  "DATABASE_DEVELOPMENT",
  "JAVA_DEVELOPMENT",
  "PYTHON_DEVELOPMENT",
  "REACT_DEVELOPMENT",
  "WORDPRESS_DEVELOPMENT",
  "TUTORING",
  "TRANSLATION",
  "FRONTEND_DEVELOPMENT",
  "PHOTOGRAPHY",
  "DATA_SCIENCE",
  "OTHER",
];

export const EXPERIENCE_LEVELS = [
  "BEGINNER",
  "INTERMEDIATE",
  "ADVANCED",
  "EXPERT",
];

export const JOB_STATUS_LABELS = {
  OPEN: "Open",
  CLOSED: "Closed",
  DRAFT: "Draft",
  DELETED: "Deleted",
};

export const APPLICATION_STATUS_LABELS = {
  APPLIED: "Applied",
  SHORTLISTED: "Shortlisted",
  REJECTED: "Rejected",
  ACCEPTED: "Accepted",
  WITHDRAWN: "Withdrawn",
};

export const PROPOSAL_STATUS_TABS = [
  "APPLIED",
  "SHORTLISTED",
  "ACCEPTED",
  "REJECTED",
  "WITHDRAWN",
];

export const CONTRACT_STATUS_LABELS = {
  PENDING: "Pending",
  ACTIVE: "Active",
  COMPLETE: "Complete",
  CANCEL: "Cancelled",
  WITHDRAWN: "Withdrawn",
};

export const PROGRESS_STATUS_LABELS = {
  NOT_STARTED: "Not Started",
  IN_PROGRESS: "In Progress",
  COMPLETED: "Completed",
};

export const PROGRESS_ORDER = ["NOT_STARTED", "IN_PROGRESS", "COMPLETED"];

export const REPORT_REASONS = [
  "INAPPROPRIATE_BEHAVIOR",
  "PAYMENT_ISSUE",
  "POOR_QUALITY_WORK",
  "MISSED_DEADLINE",
  "FRAUD_OR_SCAM",
  "OTHER",
];
